### ISSUE TITLE
Compatilibity with older versions of Qt 5

### ISSUE THREAD

**Issue by julien-mille** [pi-lemaire/annotation#2]
Qt versions anterior to 5.6 do not have QImage::pixelColor() nor QImage::setPixelColor() functions. Here is the fix for making AnnotationArea work:

AnnotationArea.cpp:line 827
#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
    if (this->ObjectImage.pixelColor(j+this->ObjectROI.left(), i+this->ObjectROI.top()).black() > 127)
        currentAnnotationMat.at<uchar>(i,j) = 255;
#else
    QRgb rgb = this->ObjectImage.pixel(j+this->ObjectROI.left(), i+this->ObjectROI.top());
    QColor col(rgb);
    if (col.black()>127)
        currentAnnotationMat.at<uchar>(i,j) = 255;
#endif

AnnotationArea.cpp:line 1298
#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
    this->PaintingImage.setPixelColor(j,i, classesColorList[this->annotations->getCurrentAnnotationsClasses().at<int16_t>(i,j)]);
#else
    QColor col = classesColorList[this->annotations->getCurrentAnnotationsClasses().at<int16_t>(i,j)];
    this->PaintingImage.setPixel(j,i,col.rgba());
#endif

I can push if you like ;)

**Comment by pi-lemaire** [comment]
This was added to the master branch, thanks for the report!
